<a href="https://colab.research.google.com/github/abhimanyubhowmik/ML_Fundamentals/blob/main/Linear_Algebra/Scalars_Vectors_and_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ## Using Scalars as tensor in Tensorflow

Tensors's can be created by:

* `tf.Variable`
* `tf.constant`
* `tf.placeholder`
* `tf.SparseTensor`




In [1]:
import tensorflow as tf

In [2]:
var = tf.Variable(5)

In [3]:
type(var)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [4]:
var.shape

TensorShape([])

In [5]:
new_var = tf.Variable(7)

In [6]:
out = var +new_var
out

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [7]:
sum = tf.add(var,new_var)
sum

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [8]:
a = sum.numpy()
a

12

In [9]:
type(a)

numpy.int32

## Using Scalars as tensor in Pytorch

In [10]:
import torch

In [11]:
a = torch.tensor(5)
a

tensor(5)

In [12]:
b = torch.tensor(6)

In [13]:
sum = torch.add(a,b)
sum

tensor(11)

## Using Vectors in Pytorch and Tensorflow

In [14]:
v = torch.tensor([3,4,5])

In [15]:
v.dim()

1

In [16]:
v.shape

torch.Size([3])

In [17]:
v.T

tensor([3, 4, 5])

In [18]:
v1 = torch.tensor([[6,7,8]])

In [19]:
v1.shape

torch.Size([1, 3])

In [20]:
v1.T

tensor([[6],
        [7],
        [8]])

In [21]:
vec = tf.Variable([[5,9,7]])

In [22]:
vec.shape

TensorShape([1, 3])

## Norms

$L^2$ Norm

In [23]:
import numpy as np

x = np.array([3,4,6])
np.linalg.norm(x)

7.810249675906654

$L^1$ Norm

In [24]:
np.linalg.norm(x,1)

13.0

Max Norm

In [25]:
np.linalg.norm(x,np.inf)

6.0

## Matrices




In [26]:
x = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
tf.rank(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [28]:
x.shape

TensorShape([3, 3])

## Tensors

In [29]:
t = torch.zeros(3,4,5,6)
t

tensor([[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0

## The Hadamard Product

The mathematical notation is $A \odot X$. It is just element wise product.

In [30]:
x

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [31]:
a = x + 2
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

In [32]:
x * a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]], dtype=int32)>

## Reduction:

Sum of all the elements in the tensor.

In [33]:
b = tf.reduce_sum(a)
b

<tf.Tensor: shape=(), dtype=int32, numpy=63>

In [34]:
v.sum()

tensor(12)

In [35]:
x_np = np.array([[1,2,3],[4,5,6],[7,8,9]])
x_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
x_np.sum(axis = 0)

array([12, 15, 18])

In [37]:
x_np.sum(axis = 1)

array([ 6, 15, 24])

## Dot Product

In [38]:
tf.reduce_sum(tf.multiply(x,a))

<tf.Tensor: shape=(), dtype=int32, numpy=375>

## Forbenious norm

$L^2$ for Matrices or tensor.

In [39]:
x_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.linalg.norm(x_np) # by default ord = forbenours norm.

16.881943016134134

In [41]:
np.linalg.norm(x_np,'fro')

16.881943016134134

## Matrix Multiplication

In [42]:
x_py = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
a_py = x_py +5

In [43]:
torch.matmul(x_py,a_py)

tensor([[ 60,  66,  72],
        [141, 156, 171],
        [222, 246, 270]])

In [44]:
tf.linalg.matmul(x,a)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]], dtype=int32)>

## Matrix Inversion

In [60]:
y_np = np.array([[5,-7,2],[8,-9,4],[6,3,-5]])

In [61]:
y_np_inv = np.linalg.inv(y_np)

In [50]:
np.linalg.det(x_np)

0.0

In [79]:
y_py = torch.tensor([[5,-7,2],[8,-9,4],[6,3,-5.]])

In [80]:
torch.inverse(y_py)

tensor([[-0.2598,  0.2283,  0.0787],
        [-0.5039,  0.2913,  0.0315],
        [-0.6142,  0.4488, -0.0866]])

In [81]:
y_tf = tf.Variable([[5,-7,2],[8,-9,4],[6,3,-5.]])

In [82]:
tf.linalg.inv(y_tf)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.2598425 ,  0.22834648,  0.07874015],
       [-0.503937  ,  0.2913386 ,  0.03149606],
       [-0.61417323,  0.4488189 , -0.08661418]], dtype=float32)>